# fly.toml app configuration file generated for vkiri-back on 2025-06-20T19:37:22+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vkiri-back'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'bundle exec rails db:migrate'

[[vm]]
  size = 'shared-cpu-1x'