
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: password
  host: db

development:
  <<: *default
  database: vtube_development

test:
  <<: *default
  database: vtube_test

production:
  primary: &primary_production
    <<: *default
    database: vtube_production
    username: app
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: app_pro1duction_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: vtube_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: vtube_production_cable
    migrations_paths: db/cable_migrate
