production:
  youtube_fetch_vspo:
    cron: "5 * * * *"
    class: "YoutubeVideoFetchJob"
    args: ["ぶいすぽっ！"]
  
  youtube_fetch_vspo_en:
    cron: "15 * * * *"
    class: "YoutubeVideoFetchJob"
    args: ["VSPO!"]

development:
  youtube_fetch_vspo:
    cron: "5 * * * *"
    class: "YoutubeVideoFetchJob"
    args: ["ぶいすぽっ！"]
