name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions@master
        with:
          version: latest
      - run: flyctl deploy --remote-only --app vkiri-back
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}